# UYGULAMA AYARLARI
spring.application.name=backend

# VİDEO YÜKLEME LİMİTLERİ (Deepfake için hayati önem taşır)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# UZUN İŞLEMLER İÇİN ZAMAN AŞIMI (Timeout engellemek için eklendi - 10 dakika)
server.tomcat.connection-timeout=600000
spring.mvc.async.request-timeout=600000
server.tomcat.max-swallow-size=-1

# VERİTABANI BAĞLANTISI (Yeni açtığın deepfake_db'ye bağlanıyor)
spring.datasource.url=jdbc:postgresql://localhost:5432/deepfake_db
spring.datasource.username="username"
spring.datasource.password="password"
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HIBERNATE (JPA) AYARLARI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ollama AYARLARI
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4
spring.ai.ollama.chat.options.temperature=0.2